dance_school_manager/client_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from client_module.views import ClientView, ClientSettingsView, AbandonCourse, CalendarView, ReportAbsenceView, \
    CoursePageViews
from employee_module.urls import login_url


app_name = 'client_module'
urlpatterns = [
    path('', login_required(ClientView.as_view(), login_url=login_url), name='user_view'),
    path('settings/', login_required(ClientSettingsView.as_view(), login_url=login_url), name='user_settings_view'),
    path('abandon/<int:pk>', login_required(AbandonCourse, login_url=login_url), name='abandon_course_view'),
    path('calendar/', login_required(CalendarView.as_view(), login_url=login_url), name='calendar_view'),
    path('report_absence/', login_required(ReportAbsenceView.as_view(), login_url=login_url),
         name='report_absence_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
]

dance_school_manager/dance_school_manager/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from authentication_module.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='main_page'),
    path('authentication/', include('authentication_module.urls')),
    path('employee/', include('employee_module.urls')),
    path('teacher/', include('teacher_module.urls')),
    path('client/', include('client_module.urls')),
]

urlpatterns += staticfiles_urlpatterns()

dance_school_manager/employee_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, register_converter

from authentication_module.models import set_absence_for_ongoing_courses
from employee_module import url_converter
from employee_module.views.course.create_course_view import CreateCourseView
from employee_module.views.course.edit_course_view import EditCourseView, remove_student_from_course
from employee_module.views.course.manage_courses_view import ManageCoursesView
from employee_module.views.default_employee_view import EmployeeHomeView
from employee_module.views.student.create_student_view import CreateStudentView
from employee_module.views.student.edit_student_view import EditStudentView, set_present, remove_course_from_student, \
    substract_deposit, remove_course_from_teacher
from employee_module.views.student.manage_student_view import ManageStudentsView
from employee_module.views.teacher.create_teacher_view import CreateTeacherView
from employee_module.views.teacher.edit_teacher_view import EditTeacherView
from employee_module.views.teacher.manage_teachers_view import ManageTeachersView

register_converter(url_converter.DateTimeConverter, 'date')
login_url = '/authentication/login'
app_name = 'employee_module'
urlpatterns = [
    path('', login_required(ManageCoursesView.as_view(), login_url=login_url), name='employee_home_view'),

    # courses
    path('create_course/', login_required(CreateCourseView.as_view(), login_url=login_url), name='create_course_view'),
    path('manage_courses/', login_required(ManageCoursesView.as_view(), login_url=login_url),
         name='manage_courses_view'),
    path('edit_course/<int:course_id>/', login_required(EditCourseView.as_view(), login_url=login_url),
         name='edit_course_view'),

    # teachers
    path('manage_teachers/', login_required(ManageTeachersView.as_view(), login_url=login_url),
         name='manage_teachers_view'),
    path('create_teachers/', login_required(CreateTeacherView.as_view(), login_url=login_url),
         name='create_teacher_view'),
    path('edit_teacher/<int:user_id>/', login_required(EditTeacherView.as_view(), login_url=login_url),
         name='edit_teacher_view'),

    # students
    path('manage_students/', login_required(ManageStudentsView.as_view(), login_url=login_url),
         name='manage_students_view'),
    path('create_student/', login_required(CreateStudentView.as_view(), login_url=login_url),
         name='create_student_view'),
    path('edit_student/<int:user_id>/', login_required(EditStudentView.as_view(), login_url=login_url),
         name='edit_student_view'),

    # mechanisms
    # path('set_absances/', set_absence_for_ongoing_courses, name='set_absance'),
    # path('substract_deposit/', substract_deposit, name='substract_deposit'),

    path('set_present/<date:date>/<int:user_id>/<int:course_id>/', set_present, name='set_present'),

    path('remove_from_course/<str:student_email>/<int:course_id>/', remove_student_from_course,
         name='remove_student_from_course'),

    path('remove_course_from_student/<str:course_name>/<int:student_id>/', remove_course_from_student,
         name='remove_course_from_student'),

    path('remove_course_from_teacher/<str:course_name>/<int:teacher_id>/', remove_course_from_teacher,
         name='remove_course_from_teacher'),


]

dance_school_manager/templates/profiles/employee/teacher/manage_teachers_view.html
{% extends 'profiles/employee/base_generic.html' %}

{% block content %}
    <div class="container">
    <form class="d-flex"
          method=POST
          action={% url 'employee_module:manage_teachers_view' %}>
        {% csrf_token %}

         <a href="{% url 'employee_module:create_teacher_view'%}">
            <button type="button" class="btn-btn-deafult">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                CREATE NEW TEACHER
            </button>
        </a>

        <input class="form-control-me-2" type="search" placeholder="Find a teacher by entering his username" aria-label="Search" name="searched">
        <button class="btn-btn-outline-secondary" type="submit"><span class="sign">&#9740;</span>
        </button>
    </form>
    <table  class="table_mc">
        <tr  class="table_mc_tr">
            <th>Name</th>
            <th>E-mail</th>
        </tr>
        {% for user in users %}
            <tr>
                <th> <a href="{% url 'employee_module:edit_teacher_view' user_id=user.id %}"> {{ user.username }} </a></th>
                <th> <a href="{% url 'employee_module:edit_teacher_view' user_id=user.id %}"> {{ user.email }} </a></th>
            </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}