dance_school_manager/client_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from client_module.views import ClientView, ClientSettingsView, AbandonCourse, CalendarView, ReportAbsenceView, \
    CoursePageViews
from employee_module.urls import login_url


app_name = 'client_module'
urlpatterns = [
    path('', login_required(ClientView.as_view(), login_url=login_url), name='user_view'),
    path('settings/', login_required(ClientSettingsView.as_view(), login_url=login_url), name='user_settings_view'),
    path('abandon/<int:pk>', login_required(AbandonCourse, login_url=login_url), name='abandon_course_view'),
    path('calendar/', login_required(CalendarView.as_view(), login_url=login_url), name='calendar_view'),
    path('report_absence/', login_required(ReportAbsenceView.as_view(), login_url=login_url),
         name='report_absence_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
]

dance_school_manager/dance_school_manager/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from authentication_module.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='main_page'),
    path('authentication/', include('authentication_module.urls')),
    path('employee/', include('employee_module.urls')),
    path('teacher/', include('teacher_module.urls')),
    path('client/', include('client_module.urls')),
]

urlpatterns += staticfiles_urlpatterns()

dance_school_manager/employee_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, register_converter

from authentication_module.models import set_absence_for_ongoing_courses
from employee_module import url_converter
from employee_module.views.course.create_course_view import CreateCourseView
from employee_module.views.course.edit_course_view import EditCourseView, remove_student_from_course
from employee_module.views.course.manage_courses_view import ManageCoursesView
from employee_module.views.default_employee_view import EmployeeHomeView
from employee_module.views.student.create_student_view import CreateStudentView
from employee_module.views.student.edit_student_view import EditStudentView, set_present, remove_course_from_student, \
    substract_deposit, remove_course_from_teacher
from employee_module.views.student.manage_student_view import ManageStudentsView
from employee_module.views.teacher.create_teacher_view import CreateTeacherView
from employee_module.views.teacher.edit_teacher_view import EditTeacherView
from employee_module.views.teacher.manage_teachers_view import ManageTeachersView

register_converter(url_converter.DateTimeConverter, 'date')
login_url = '/authentication/login'
app_name = 'employee_module'
urlpatterns = [
    path('', login_required(ManageCoursesView.as_view(), login_url=login_url), name='employee_home_view'),

    # courses
    path('create_course/', login_required(CreateCourseView.as_view(), login_url=login_url), name='create_course_view'),
    path('manage_courses/', login_required(ManageCoursesView.as_view(), login_url=login_url),
         name='manage_courses_view'),
    path('edit_course/<int:course_id>/', login_required(EditCourseView.as_view(), login_url=login_url),
         name='edit_course_view'),

    # teachers
    path('manage_teachers/', login_required(ManageTeachersView.as_view(), login_url=login_url),
         name='manage_teachers_view'),
    path('create_teachers/', login_required(CreateTeacherView.as_view(), login_url=login_url),
         name='create_teacher_view'),
    path('edit_teacher/<int:user_id>/', login_required(EditTeacherView.as_view(), login_url=login_url),
         name='edit_teacher_view'),

    # students
    path('manage_students/', login_required(ManageStudentsView.as_view(), login_url=login_url),
         name='manage_students_view'),
    path('create_student/', login_required(CreateStudentView.as_view(), login_url=login_url),
         name='create_student_view'),
    path('edit_student/<int:user_id>/', login_required(EditStudentView.as_view(), login_url=login_url),
         name='edit_student_view'),

    # mechanisms
    # path('set_absances/', set_absence_for_ongoing_courses, name='set_absance'),
    # path('substract_deposit/', substract_deposit, name='substract_deposit'),

    path('set_present/<date:date>/<int:user_id>/<int:course_id>/', set_present, name='set_present'),

    path('remove_from_course/<str:student_email>/<int:course_id>/', remove_student_from_course,
         name='remove_student_from_course'),

    path('remove_course_from_student/<str:course_name>/<int:student_id>/', remove_course_from_student,
         name='remove_course_from_student'),

    path('remove_course_from_teacher/<str:course_name>/<int:teacher_id>/', remove_course_from_teacher,
         name='remove_course_from_teacher'),


]

dance_school_manager/courses_module/models.py
from datetime import timedelta, date, datetime
from time import time

from django.db import models

from dance_school_manager.settings import HOUR_FORMAT, DAYS_OF_WEEK


class Courses(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    room = models.IntegerField(default=0)
    start_date = models.DateField()
    days = models.CharField(choices=DAYS_OF_WEEK, default='Monday', max_length=70)
    time = models.TimeField()
    end_date = models.DateField()

    def __str__(self):
        return f'Course {self.name}: {self.description}'

    @property
    def lesson_end(self) -> time:
        end_date = datetime.combine(date.today(), self.time) + timedelta(minutes=45)
        return end_date.time()

    def is_ongoing(self, time_delta: timedelta = timedelta(minutes=0)):
        current_time: time = datetime.now() + time_delta
        if self.start_date <= current_time.date() < self.end_date:
            if int(self.days) == current_time.weekday():
                if self.time.strftime(HOUR_FORMAT) <= current_time.time().strftime(
                        HOUR_FORMAT) < self.lesson_end.strftime(HOUR_FORMAT):
                    return True
        return False


class Exceptions(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField()
    description = models.CharField(max_length=100)
    related_course = models.ForeignKey(Courses, on_delete=models.CASCADE)

    def __str__(self):
        return f'Exception: {self.name} : {self.description}'


class GeneralException(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField()
    description = models.CharField(max_length=100)

    def __str__(self):
        return f'GeneralException: {self.name} : {self.description}'

dance_school_manager/employee_module/views/edit_course_view.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View

from authentication_module.models import CustomUser
from courses_module.models import Courses
from employee_module.forms.create_course_form import CreateCourseForm


class EditCoursesViews(View):
    template_name = 'profiles/employee/edit_course_view.html'

    def get(self, request, course_id: int):
        course = get_object_or_404(Courses, id=course_id)
        students_attended_to_this_course = CustomUser.objects.filter(courses__id=course_id)

        course_form = CreateCourseForm(initial={'name': course.name, 'description': course.description})
        for i, student in enumerate(students_attended_to_this_course):
            course_form.initial.update({f'{i}_student': student.email})
            return render(request, self.template_name, {'course_form': course_form})

    def post(self, request, course_id: int, *args, **kwargs):
        course_form = CreateCourseForm(request.POST)
        if course_form.is_valid():
            course = Courses.objects.get(id=course_id)
            emails_not_found = []
            for student in course_form.fields.keys():
                email = course_form.cleaned_data[student]
                if student.endswith('student') and email:
                    try:
                        self.assign_course_to_student_by(email=email, course=course)
                    except CustomUser.DoesNotExist:
                        emails_not_found.append(email)
            if emails_not_found:
                return render(request, self.template_name,
                              {'course_form': course_form, 'emails_not_found': emails_not_found})
            course.save()
            return HttpResponse(f'You created course {str(course)}, and proper')
        else:
            return HttpResponse('Sorry not now')

    @classmethod
    def assign_course_to_student_by(cls, email, course):
        user = CustomUser.objects.get(email=email)
        user.save()
        course.save()
        if user.is_student:
            user.courses.add(course)
        else:
            raise CustomUser.DoesNotExist

dance_school_manager/templates/profiles/employee/course/create_course_view.html
{% extends 'profiles/employee/base_generic.html' %}
{% block content %}
<div class="info">
    {% if emails_not_found %}
        <p>Given emails are not found in student register!</p>
        {% for email in emails_not_found %}
            <p>{{ email }}</p>
        {% endfor %}
    {% endif %}
</div>
<div class="container">
    <form class="form_mc" method="post">
        {% csrf_token %}
        <table class="table_mc1">
            <tr>
                <th><label for="id_name">Course name:</label></th>
                <th><input type="text" name="name" maxlength="20" required="" id="id_name"></th>
            </tr>
            <tr>
                <th><label for="id_room">Room:</label></th>
                <th><input type="number" name="room" required="" id="id_room"></th>
            </tr>
            <tr>
                <th><label for="id_description">Description:</label></th>
                <th><input type="text" name="description" maxlength="100" required="" id="id_description"></th>
            </tr>
            <tr>
                <th><label for="id_start_date">Start date:</label></th>
                <th><input type="date" name="start_date" required="" id="id_start_date"></th>
            </tr>
            <tr>
                <th><label for="id_end_date">End date:</label></th>
                <th><input type="date" name="end_date" required="" id="id_end_date"></th>
            </tr>
            <tr>
                <th><label for="id_days">Days:</label></th>
                <th><select name="days" maxlength="70" id="id_days">
                  <option value="0">Monday</option>
                  <option value="1">Tuesday</option>
                  <option value="2">Wednesday</option>
                  <option value="3">Thursday</option>
                  <option value="4">Friday</option>
                  <option value="5">Saturday</option>
                  <option value="6">Sunday</option>
                </select></th>
            </tr>
            <tr>
                <th><label for="id_time">Time:</label></th>
                <th><input type="time" name="time" required="required" id="id_time"></th>
            </tr>
            <tr>
                <th><label for="id_0_student">Student 0 email:</label></th>
                <th><input type="email" name="0_student" maxlength="100" id="id_0_student"></th>
            </tr>
            <tr>
                <th><label for="id_1_student">Student 1 email:</label></th>
                <th><input type="email" name="1_student" maxlength="100" id="id_1_student"></th>
            </tr>
            <tr>
                <th><label for="id_2_student">Student 2 email:</label></th>
                <th><input type="email" name="2_student" maxlength="100" id="id_2_student"></th>
            </tr>
            <tr>
                <th><label for="id_3_student">Student 3 email:</label></th>
                <th><input type="email" name="3_student" maxlength="100" id="id_3_student"></th>
            </tr>
            <tr>
                <th><label for="id_4_student">Student 4 email:</label></th>
                <th><input type="email" name="4_student" maxlength="100" id="id_4_student"></th>
            </tr>
            <tr>
                <th><label for="id_5_student">Student 5 email:</label></th>
                <th><input type="email" name="5_student" maxlength="100" id="id_5_student"></th>
            </tr>
            <tr>
                <th><label for="id_6_student">Student 6 email:</label></th>
                <th><input type="email" name="6_student" maxlength="100" id="id_6_student"></th>
        </table>
        <table class="table_mc2">
            </tr>
            <tr>
                <th><label for="id_7_student">Student 7 email:</label></th>
                <th><input type="email" name="7_student" maxlength="100" id="id_7_student"></th>
            </tr>
            <tr>
                <th><label for="id_8_student">Student 8 email:</label></th>
                <th><input type="email" name="8_student" maxlength="100" id="id_8_student"></th>
            </tr>
            <tr>
                <th><label for="id_9_student">Student 9 email:</label></th>
                <th><input type="email" name="9_student" maxlength="100" id="id_9_student"></th>
            </tr>
            <tr>
                <th><label for="id_10_student">Student 10 email:</label></th>
                <th><input type="email" name="10_student" maxlength="100" id="id_10_student"></th>
            </tr>
            <tr>
                <th><label for="id_11_student">Student 11 email:</label></th>
                <th><input type="email" name="11_student" maxlength="100" id="id_11_student"></th>
            </tr>
            <tr>
                <th><label for="id_12_student">Student 12 email:</label></th>
                <th><input type="email" name="12_student" maxlength="100" id="id_12_student"></th>
            </tr>
            <tr>
                <th><label for="id_13_student">Student 13 email:</label></th>
                <th><input type="email" name="13_student" maxlength="100" id="id_13_student"></th>
            </tr>
            <tr>
                <th><label for="id_14_student">Student 14 email:</label></th>
                <th><input type="email" name="14_student" maxlength="100" id="id_14_student"></th>
            </tr>
            <tr>
                <th><label for="id_15_student">Student 15 email:</label></th>
                <th><input type="email" name="15_student" maxlength="100" id="id_15_student"></th>
            </tr>
            <tr>
                <th><label for="id_16_student">Student 16 email:</label></th>
                <th><input type="email" name="16_student" maxlength="100" id="id_16_student"></th>
            </tr>
            <tr>
                <th><label for="id_17_student">Student 17 email:</label></th>
                <th><input type="email" name="17_student" maxlength="100" id="id_17_student"></th>
            </tr>
            <tr>
                <th><label for="id_18_student">Student 18 email:</label></th>
                <th><input type="email" name="18_student" maxlength="100" id="id_18_student"></th>
            </tr>
            <tr>
                <th><label for="id_19_student">Student 19 email:</label></th>
                <th><input type="email" name="19_student" maxlength="100" id="id_19_student"></th>
            </tr>
            <tr>
                <th colspan="1">
                        <button id="input_an">
                            <a href="{% url 'employee_module:manage_courses_view' %}" id="input_an">
                                ANULUJ </a>
                        </button>
                    </th>
                <th colspan="1"><input id="input_mc" type="submit" value="Submit"></th>
            </tr>
        </table>

    </form>
    </div>
{% endblock %}

dance_school_manager/templates/profiles/employee/course/edit_course_view.html
{% extends 'profiles/employee/base_generic.html' %}
{% block content %}
    <div class="info">
        {% if emails_not_found %}
            <p>Given emails are not found in student register!</p>
            {% for email in emails_not_found %}
                <p>{{ email }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div class="container">
        <form class="form_mc" method="post">
            {% csrf_token %}
            <table class="table_mc1">
                <tr>
                    <th>Course name:</th>
                    <th>{{ course_form.name }}</th>
                </tr>
                <tr>
                    <th>Room:</th>
                    <th>{{ course_form.room }}</th>
                </tr>
                <tr>
                    <th>Description:</th>
                    <th>{{ course_form.description }}</th>
                </tr>
                <tr>
                    <th>Start date:</th>
                    <th>{{ course_form.start_date }}</th>
                </tr>
                <tr>
                    <th>End date:</th>
                    <th>{{ course_form.end_date }}</th>
                </tr>
                <tr>
                    <th>Days:</th>
                    <th>{{ course_form.days }}</th>
                </tr>
                <tr>
                    <th>Time:</th>
                    <th>{{ course_form.time }}</th>
                </tr>
                <tr>
                    <th>Student 0 email:</th>
                    <th>{{ course_form.0_student }}</th>
                    {% if course_form.0_student.value %}
                        <td>
                            <button>
                                <a href="{% url 'employee_module:remove_student_from_course' course_form.0_student.value  course_id %}">
                                    X </a>
                            </button>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 1 email:</th>
                    <th>{{ course_form.1_student }}</th>
                    {% if course_form.1_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.1_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 2 email:</th>
                    <th>{{ course_form.2_student }}</th>
                    {% if course_form.2_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.2_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 3 email:</th>
                    <th>{{ course_form.3_student }}</th>
                    {% if course_form.3_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.3_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 4 email:</th>
                    <th>{{ course_form.4_student }}</th>
                    {% if course_form.4_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.4_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 5 email:</th>
                    <th>{{ course_form.5_student }}</th>
                    {% if course_form.5_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.5_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 6 email:</th>
                    <th>{{ course_form.6_student }}</th>
                    {% if course_form.6_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.6_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
            </table>
            <table class="table_mc2">
                </tr>
                <tr>
                    <th>Student 7 email:</th>
                    <th>{{ course_form.7_student }}</th>
                    {% if course_form.7_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.7_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 8 email:</th>
                    <th>{{ course_form.8_student }}</th>
                    {% if course_form.8_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.8_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 9 email:</th>
                    <th>{{ course_form.9_student }}</th>
                    {% if course_form.9_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.9_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 10 email:</th>
                    <th>{{ course_form.10_student }}</th>
                    {% if course_form.10_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.10_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 11 email:</th>
                    <th>{{ course_form.11_student }}</th>
                    {% if course_form.11_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.11_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 12 email:</th>
                    <th>{{ course_form.12_student }}</th>
                    {% if course_form.12_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.12_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 13 email:</th>
                    <th>{{ course_form.13_student }}</th>
                    {% if course_form.13_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.13_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 14 email:</th>
                    <th>{{ course_form.14_student }}</th>
                    {% if course_form.14_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.14_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 15 email:</th>
                    <th>{{ course_form.15_student }}</th>
                    {% if course_form.15_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.15_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 16 email:</th>
                    <th>{{ course_form.16_student }}</th>
                    {% if course_form.16_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.16_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 17 email:</th>
                    <th>{{ course_form.17_student }}</th>
                    {% if course_form.17_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.17_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 18 email:</th>
                    <th>{{ course_form.18_student }}</th>
                    {% if course_form.18_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.18_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Student 19 email:</th>
                    <th>{{ course_form.19_student }}</th>
                    {% if course_form.19_student.value %}
                        <td>
                            <a href="{% url 'employee_module:remove_student_from_course' course_form.19_student.value  course_id %}">
                                X </a>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <th colspan="1">
                        <button id="input_an">
                            <a href="{% url 'employee_module:manage_courses_view' %}" id="input_an">
                                ANULUJ </a>
                        </button>
                    </th>
                    <th colspan="1"><input id="input_mc" type="submit" value="SUBMIT"></th>
                </tr>

            </table>

        </form>
    </div>
{% endblock %}

dance_school_manager/templates/profiles/employee/course/manage_courses_view.html
{% extends 'profiles/employee/base_generic.html' %}
{% block content %}
    <div class="container">
    <form class="d-flex"
          method=POST
          action={% url 'employee_module:manage_courses_view' %}>
        {% csrf_token %}
        <a href="{% url 'employee_module:create_course_view' %}">
        <button type="button" class="btn-btn-deafult">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            CREATE NEW COURSE
        </button>
    </a>
        <input class="form-control-me-2" type="search" placeholder="Find a course by entering its name" aria-label="Search" name="searched">
        <button class="btn-btn-outline-secondary"
                type="submit"><span class="sign">&#9740;</span>
        </button>
    </form>
    <table  class="table_mc">
        <tr  class="table_mc_tr">
            <th>Name</th>
            <th>Description</th>
        </tr>
        {% for course in courses %}
            <tr>
                <th><a href="{% url 'employee_module:edit_course_view' course_id=course.id %}"> {{ course.name }}</a></th>
                <th> <a href="{% url 'employee_module:edit_course_view' course_id=course.id %}">{{ course.description }}</a></th>
            </tr>
        {% endfor %}
    </table>


    </div>
{% endblock %}