dance_school_manager/client_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from client_module.views import ClientView, ClientSettingsView, AbandonCourse, CalendarView, ReportAbsenceView, \
    CoursePageViews
from employee_module.urls import login_url


app_name = 'client_module'
urlpatterns = [
    path('', login_required(ClientView.as_view(), login_url=login_url), name='user_view'),
    path('settings/', login_required(ClientSettingsView.as_view(), login_url=login_url), name='user_settings_view'),
    path('abandon/<int:pk>', login_required(AbandonCourse, login_url=login_url), name='abandon_course_view'),
    path('calendar/', login_required(CalendarView.as_view(), login_url=login_url), name='calendar_view'),
    path('report_absence/', login_required(ReportAbsenceView.as_view(), login_url=login_url),
         name='report_absence_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
]

dance_school_manager/dance_school_manager/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from authentication_module.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='main_page'),
    path('authentication/', include('authentication_module.urls')),
    path('employee/', include('employee_module.urls')),
    path('teacher/', include('teacher_module.urls')),
    path('client/', include('client_module.urls')),
]

urlpatterns += staticfiles_urlpatterns()

dance_school_manager/teacher_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from employee_module.urls import login_url
from teacher_module.views.calendar import CalendarViews
from teacher_module.views.contact_view import contact_view
from teacher_module.views.course_page import CoursePageViews, CoursesViews
from teacher_module.views.create_message import MessagePostView
from teacher_module.views.main_view import TeacherView
from teacher_module.views.settings_view import SettingsViews
from teacher_module.views.view_courses import CoursesListViews

app_name = "teacher_module"

urlpatterns = [
    path('', login_required(TeacherView.as_view(), login_url=login_url), name='teacher_profile_view'),
    path('courses_list/', login_required(CoursesListViews.as_view(), login_url=login_url), name='courses_list_view'),
    path('settings/', login_required(SettingsViews.as_view(), login_url=login_url), name='settings_view'),
    path('calendar/', login_required(CalendarViews.as_view(), login_url=login_url), name='calendar_view'),
    path('courses/', login_required(CoursesViews.as_view(), login_url=login_url), name='courses_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
    path('certain_course/create_message/', login_required(MessagePostView.as_view(), login_url=login_url),
         name='create_message_view'),
    path('contacts/', contact_view, name='contact_view')
]

dance_school_manager/courses_module/models.py
from datetime import timedelta, date, datetime
from time import time

from django.db import models

from dance_school_manager.settings import HOUR_FORMAT, DAYS_OF_WEEK


class Courses(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    room = models.IntegerField(default=0)
    start_date = models.DateField()
    days = models.CharField(choices=DAYS_OF_WEEK, default='Monday', max_length=70)
    time = models.TimeField()
    end_date = models.DateField()

    def __str__(self):
        return f'Course {self.name}: {self.description}'

    @property
    def lesson_end(self) -> time:
        end_date = datetime.combine(date.today(), self.time) + timedelta(minutes=45)
        return end_date.time()

    def is_ongoing(self, time_delta: timedelta = timedelta(minutes=0)):
        current_time: time = datetime.now() + time_delta
        if self.start_date <= current_time.date() < self.end_date:
            if int(self.days) == current_time.weekday():
                if self.time.strftime(HOUR_FORMAT) <= current_time.time().strftime(
                        HOUR_FORMAT) < self.lesson_end.strftime(HOUR_FORMAT):
                    return True
        return False


class Exceptions(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField()
    description = models.CharField(max_length=100)
    related_course = models.ForeignKey(Courses, on_delete=models.CASCADE)

    def __str__(self):
        return f'Exception: {self.name} : {self.description}'


class GeneralException(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField()
    description = models.CharField(max_length=100)

    def __str__(self):
        return f'GeneralException: {self.name} : {self.description}'

dance_school_manager/teacher_module/views/calendar.py
from django.shortcuts import render
from django.views.generic import CreateView


class CalendarViews(CreateView):
    template = 'profiles/teacher/calendar_view.html'

    def get(self, request, *args, **kwargs):
        courses_list = request.user.courses.all()
        monday = [course for course in courses_list if course.days == '0']
        tuesday = [course for course in courses_list if course.days == '1']
        wednesday = [course for course in courses_list if course.days == '2']
        thursday = [course for course in courses_list if course.days == '3']
        friday = [course for course in courses_list if course.days == '4']

        context = {'monday': monday,
                   'tuesday': tuesday,
                   'wednesday': wednesday,
                   'thursday': thursday,
                   'friday': friday,
                   'user': request.user, }

        return render(request, self.template, context=context)

dance_school_manager/teacher_module/views/course_page.py
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.generic import CreateView

from authentication_module.models import CustomUser
from courses_module.models import Courses
from teacher_module.models import Message


class CoursesViews(CreateView):
    template_name = 'profiles/teacher/courses.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        context = {'username': request.user.username,
                   'courses_list': request.user.courses.all()
                   }
        return render(request, self.template_name, context=context)


class CoursePageViews(CreateView):
    template_name = 'profiles/teacher/course_page.html'

    @method_decorator(login_required)
    def get(self, request, course_id: int):
        course = get_object_or_404(Courses, id=course_id)
        students_attended_to_this_course: QuerySet = CustomUser.objects.filter(courses__id=course_id)

        certain_course = Courses.objects.get(id=course_id)

        # filter messages assignet to certain course
        messages_assigned_to_this_course: QuerySet = Message.objects.filter(related_course=course_id)



        context = {'username': request.user.username,
                   'courses_list': request.user.courses.all(),
                   'course_id': course_id,
                   'certain_course': certain_course,
                   'students_attended': students_attended_to_this_course,
                   'messages_assigned_to_this_course': messages_assigned_to_this_course

                   }

        return render(request, self.template_name, context=context)

dance_school_manager/templates/profiles/student/abandon_course.html
{% extends 'profiles/student/base_generic.html' %}
{% block content %}
<div class="abandon centered">
    <p>Are you sure you want to leave the course "{{item.name}}"?</p>
    <form method="POST">
        {% csrf_token %}
        <tr>
            <th>
                <a href="{% url 'client_module:user_view' %}">
                    <button type="button" class="btn btn-deafult">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        Go Back
                    </button>
                </a>
            </th>
            <th>
                <input type="submit" name="Confirm">
            </th>
        </tr>
    </form>
</div>
{% endblock %}

dance_school_manager/templates/profiles/student/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/student.css">
</head>
<body>
<div class="row">
    <div class="col-md-8 col-sm-10 col-12">
        {{ profile }}
    </div>
</div>
{% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
{% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

dance_school_manager/templates/profiles/student/calendar_view.html
{% extends 'profiles/student/base_generic.html' %}
{% block content %}

<div class="calendar title">
                <table class="table1" style="width:100%">
                    <tr>
                        <th class="title"> Nazwa </th>
                        <th class="title"> Pokoj </th>
                        <th class="title"> Czas </th>
                    </tr>
                </table>
        {% for day in days %}
            <h2 class="big-border">{{ day.0 }}</h2>
            {% for course in day.1 %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th class="title"> {{ course.name }}</th>
                        <th class="title"> {{ course.room }}</th>
                        <th class="title"> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endfor %}
</div>
<div class="button submit-btn">
    <a href="{% url 'client_module:user_view' %}">Go Back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/student/course_page_view.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<div class="hello">
    <h2> Welcome {{ username }} to the "{{ certain_course.name }}" course page! </h2>
</div>
<div class="coursepage-container">
  <div class="coursepage-child left">
    <h2 class="title"> List of Participants</h2>
    <table class="title" style="width:100%">
            <tr>
                <th> Participant Name:</th>
                <th> Participant Email:</th>
            </tr>
        {% for student in students_attended %}
            <tr>
                <td> {{ student.username }}</td>
                <td> {{ student.email }}</td>
            </tr>
        {% endfor %}
    </table>
  </div>
  <div class="coursepage-child right">
    <h2 class="title"> Message box</h2>
    <table class="title" style="width:100%">
     <tr>
         <th> Title:</th>
         <th> Message:</th>
         <th> Date posted:</th>
     </tr>
     {% for messages in messages_assigned_to_this_course %}
     <tr>
         <td> {{ messages.title }} </td>
         <td> {{ messages.text }} </td>
         <td> {{ messages.date_created }} </td>

     </tr>
    {% endfor %}
    </table>
  </div>
</div>
<div class="button submit-btn">
    <a href="{% url 'client_module:user_view' %}">Go back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/student/report_absence_view.html
{% extends 'profiles/student/base_generic.html' %}
{% block content %}
<div class="abandon centered">
    <h3>Report Absence</h3>

    <form enctype="multipart/form-data" method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post"/>
    </form>

<!--        <form enctype="multipart/form-data" method="POST" action="">-->
<!--            <input type="hidden" name="csrfmiddlewaretoken" value="ds56HSHgRJS3H42hsMbd3K0DGAALI3IaEW1uuKvZ0DUgCitMUqCsG9x1Ug6fbWwX">-->
<!--            <p><label for="id_date">Date:</label> <input type="date" name="date" required="" id="id_date"></p>-->
<!--            <p><label for="id_related_course">Related course:</label> <select name="related_course" required="" id="id_related_course">-->
<!--            <option value="" selected="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--            <option value="1">Course TestCourse: Some test</option>-->
<!--            </select></p>-->
<!--            <input type="submit" value="Post">-->
<!--    </form>-->

</div>
<div class="button submit-btn">
    <a href="{% url 'client_module:user_view' %}">Go Back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/student/student_profile.html
{% extends 'profiles/student/base_generic.html' %}

{% block content %}

<div class="contrainer">
    <div class="main">
        <div class="topbar">
            <button class="submit-btn" onclick="location.href = '/authentication/logout/'" type="button">
                LOGOUT
            </button>
            <button class="submit-btn" onclick="location.href = '{% url 'teacher_module:contact_view' %}'" type="button">
                CONTACT
            </button>
        </div>
        <div class="row">
            <div class="col-md-4 mt-1">
                <div class="card text-center sidebar">
                    <div class="card-body">
                        <!--
                        {% load static %}
                        <img src="{{ avatar }}" alt="profile avatar"/>
                        -->
                        <img src="/static/images/profile.jpg" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h3>{{ user.username }}</h3>
                            <a href="{% url 'client_module:user_settings_view' %}">Edit Profile</a>
                            <a href="{% url 'client_module:calendar_view' %}">Calendar</a>
                            <a href="{% url 'client_module:report_absence_view' %}">Report Absence</a>
                        </div>
                    </div>
                </div>
            </div>
            				<div class="col-md-8 mt-1">
            				    <div class="card mb-3 content">
                				    <h1 class="m-3 pt-3">About</h1>
                    				<div class="card-body">
                    					<div class="row">
                        					<div class="col-md-3">
                            						<h5>Fist Name</h5>
								            </div>
                            					<div class="col-md-9 text-secondary">
                            						{{ user.name}}
								                </div>
							            </div>
							            <hr>
                    					<div class="row">
                        					<div class="col-md-3">
                            						<h5>Last Name</h5>
								            </div>
                            					<div class="col-md-9 text-secondary">
                            						{{ user.surname }}
								                </div>
							            </div>
							            <hr>
                                        <div class="row">
                                            <div class="col-md-3">
                                                <h5>Email</h5>
                                            </div>
                                            <div class="col-md-9 text-secondary">
                                                {{ user.email }}
                                            </div>
                                        </div>
							            <hr>
                                        <div class="row">
                                            <div class="col-md-3">
                                                <h5>Current Deposit</h5>
                                            </div>
                                            <div class="col-md-9 text-secondary">
                                                {{ deposit }}
                                            </div>
							            </div>
                                    </div>
                                </div>
						    </div>
					</div>
        <div class="card mb-3c content">
            <table>
            <tr>
                <th> Name of the course</th>
                <th> Description</th>
                <th> Course start date</th>
                <th> Course end date</th>
                <th> Course page</th>
                <th> Abandon Course </th>

            </tr>
        {% for course in courses_list %}
            <tr>
                <td> {{ course.name }}</td>
                <td> {{ course.description }}</td>
                <td> {{ course.start_date }}</td>
                <td> {{ course.end_date }}</td>
                <td>
                    <button>
                        <a href="{% url 'client_module:course_page_view' course_id=course.id %}"> Check details</a>
                    </button>
                </td>
                <td>
                    <a href="{% url 'client_module:abandon_course_view' pk=course.id %}">
                        <button type="button" class="btn btn-deafult">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Abandon
                        </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </table>
</div>
{% endblock %}

dance_school_manager/templates/profiles/student/student_profile_settings.html
{% extends 'profiles/student/base_generic.html' %}
{% block content %}
<style>
body {
  	text-align: center;
}
</style>


<div class="course centered">
		<h3>Input your new data</h3>
		<div class="flexbox-item flexbox-item-1">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button class ="btn btn-secondary">Update</button>
            </form>
		</div>
</div>
<div class="button submit-btn">
    <a href="{% url 'client_module:user_view' %}">Go Back</a>
</div>
{% endblock %}