dance_school_manager/client_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from client_module.views import ClientView, ClientSettingsView, AbandonCourse, CalendarView, ReportAbsenceView, \
    CoursePageViews
from employee_module.urls import login_url


app_name = 'client_module'
urlpatterns = [
    path('', login_required(ClientView.as_view(), login_url=login_url), name='user_view'),
    path('settings/', login_required(ClientSettingsView.as_view(), login_url=login_url), name='user_settings_view'),
    path('abandon/<int:pk>', login_required(AbandonCourse, login_url=login_url), name='abandon_course_view'),
    path('calendar/', login_required(CalendarView.as_view(), login_url=login_url), name='calendar_view'),
    path('report_absence/', login_required(ReportAbsenceView.as_view(), login_url=login_url),
         name='report_absence_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
]

dance_school_manager/dance_school_manager/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from authentication_module.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='main_page'),
    path('authentication/', include('authentication_module.urls')),
    path('employee/', include('employee_module.urls')),
    path('teacher/', include('teacher_module.urls')),
    path('client/', include('client_module.urls')),
]

urlpatterns += staticfiles_urlpatterns()

dance_school_manager/teacher_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from employee_module.urls import login_url
from teacher_module.views.calendar import CalendarViews
from teacher_module.views.contact_view import contact_view
from teacher_module.views.course_page import CoursePageViews, CoursesViews
from teacher_module.views.create_message import MessagePostView
from teacher_module.views.main_view import TeacherView
from teacher_module.views.settings_view import SettingsViews
from teacher_module.views.view_courses import CoursesListViews

app_name = "teacher_module"

urlpatterns = [
    path('', login_required(TeacherView.as_view(), login_url=login_url), name='teacher_profile_view'),
    path('courses_list/', login_required(CoursesListViews.as_view(), login_url=login_url), name='courses_list_view'),
    path('settings/', login_required(SettingsViews.as_view(), login_url=login_url), name='settings_view'),
    path('calendar/', login_required(CalendarViews.as_view(), login_url=login_url), name='calendar_view'),
    path('courses/', login_required(CoursesViews.as_view(), login_url=login_url), name='courses_view'),
    path('certain_course/<int:course_id>/', login_required(CoursePageViews.as_view(), login_url=login_url),
         name='course_page_view'),
    path('certain_course/create_message/', login_required(MessagePostView.as_view(), login_url=login_url),
         name='create_message_view'),
    path('contacts/', contact_view, name='contact_view')
]

dance_school_manager/teacher_module/forms/create_message_form.py
from django import forms

from authentication_module.models import CustomUser
from courses_module.models import Courses
from teacher_module.models import Message


class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = Message
       # fields = ["title", "text", "user", "related_course"]
        exclude = ["user"]

dance_school_manager/teacher_module/views/calendar.py
from django.shortcuts import render
from django.views.generic import CreateView


class CalendarViews(CreateView):
    template = 'profiles/teacher/calendar_view.html'

    def get(self, request, *args, **kwargs):
        courses_list = request.user.courses.all()
        monday = [course for course in courses_list if course.days == '0']
        tuesday = [course for course in courses_list if course.days == '1']
        wednesday = [course for course in courses_list if course.days == '2']
        thursday = [course for course in courses_list if course.days == '3']
        friday = [course for course in courses_list if course.days == '4']

        context = {'monday': monday,
                   'tuesday': tuesday,
                   'wednesday': wednesday,
                   'thursday': thursday,
                   'friday': friday,
                   'user': request.user, }

        return render(request, self.template, context=context)

dance_school_manager/teacher_module/views/contact_view.py
from django.shortcuts import render


def contact_view(request):
    return render(request, template_name='profiles/teacher/contact.html')

dance_school_manager/teacher_module/views/course_page.py
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.generic import CreateView

from authentication_module.models import CustomUser
from courses_module.models import Courses
from teacher_module.models import Message


class CoursesViews(CreateView):
    template_name = 'profiles/teacher/courses.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        context = {'username': request.user.username,
                   'courses_list': request.user.courses.all()
                   }
        return render(request, self.template_name, context=context)


class CoursePageViews(CreateView):
    template_name = 'profiles/teacher/course_page.html'

    @method_decorator(login_required)
    def get(self, request, course_id: int):
        course = get_object_or_404(Courses, id=course_id)
        students_attended_to_this_course: QuerySet = CustomUser.objects.filter(courses__id=course_id)

        certain_course = Courses.objects.get(id=course_id)

        # filter messages assignet to certain course
        messages_assigned_to_this_course: QuerySet = Message.objects.filter(related_course=course_id)



        context = {'username': request.user.username,
                   'courses_list': request.user.courses.all(),
                   'course_id': course_id,
                   'certain_course': certain_course,
                   'students_attended': students_attended_to_this_course,
                   'messages_assigned_to_this_course': messages_assigned_to_this_course

                   }

        return render(request, self.template_name, context=context)

dance_school_manager/teacher_module/views/create_message.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView

from teacher_module.forms.create_message_form import CreateMessageForm


class MessagePostView(CreateView):

    def get(self, request, *args, **kwargs):
        form = CreateMessageForm(request.POST or None)
        context = {'form': form,
                   }
        return render(request, 'profiles/teacher/create_message.html', context)

    def post(self, request, *args, **kwargs):
        form = CreateMessageForm(request.POST)
        form.instance.user = request.user
        if request.method == "POST":
            if form.is_valid():
                related_course = form.cleaned_data.get("related_course")
                form.save()
                return redirect("teacher_module:course_page_view", course_id=related_course.id)


        context = {'form': form,
           # 'userlist':userlist
           }

        return render(request, 'profiles/teacher/create_message.html', context)

dance_school_manager/teacher_module/views/settings_view.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import  generic
from django.views.generic import CreateView, DeleteView, UpdateView
from django.contrib.auth.forms import UserChangeForm


from authentication_module.models import CustomUser



#class SettingsViews(View):


 #   def get(self, request, customuser_id: int):
  #      teacher = get_object_or_404(CustomUser, id=customuser_id) #pobieram konkretnego nauczyciela o podanym id jesli go nie ma to strona z 404

   # form = UserChangeForm
    #template_name = 'profiles/teacher/settings.html'
    #success_url = reverse_lazy('teacher_module:user_view')
    #fields = {'email', 'username'} #teacher can edit given data

    #def get_object(self):
    #   return self.request.user

    # Client can edit parameters given in field
class SettingsViews(UpdateView):
    form = UserChangeForm
    template_name = 'profiles/teacher/settings.html'
    success_url = reverse_lazy('teacher_module:teacher_profile_view')
    fields = {'email', 'username', 'name', 'surname'}

    def get_object(self):
        return self.request.user

dance_school_manager/teacher_module/views/view_courses.py
from django.contrib.auth.decorators import login_required
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.generic import CreateView, DeleteView, UpdateView
from django.contrib.auth.forms import UserChangeForm
from authentication_module.forms import EditProfileForm


class CoursesListViews(CreateView):
    template_name = 'profiles/teacher/view_courses.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        context = {'user': request.user,
                   'courses_list': request.user.courses.all()
                   }

        return render(request, self.template_name, context=context)

dance_school_manager/templates/profiles/teacher/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/teacher.css">
</head>
<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

dance_school_manager/templates/profiles/teacher/calendar_view.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<div class="calendar title">
    <table  class="table1" style="width:100%">
        <h2 class="big-border"></h2>
                    <tr>
                        <th> Course Name</th>
                        <th> Course Room</th>
                        <th> Course Time</th>
                    </tr>
                </table >
    <h2 class="big-border">Monday</h2>
        {% if monday %}
            {% for course in monday %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th> {{ course.name }}</th>
                        <th> {{ course.room }}</th>
                        <th> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endif %}
    <h2 class="big-border">Tuesday</h2>
        {% if tuesday %}
            {% for course in tuesday %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th> {{ course.name }}</th>
                        <th> {{ course.room }}</th>
                        <th> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endif %}
    <h2 class="big-border">Wednesday</h2>
        {% if wednesday %}
            {% for course in wednesday %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th> {{ course.name }}</th>
                        <th> {{ course.room }}</th>
                        <th> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endif %}
    <h2 class="big-border">Thursday</h2>
        {% if thursday %}
            {% for course in thursday %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th> {{ course.name }}</th>
                        <th> {{ course.room }}</th>
                        <th> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endif %}
    <h2 class="big-border">Friday</h2>
        {% if friday %}
            {% for course in friday %}
                <table class="table1" style="width:100%">
                    <tr>
                        <th> {{ course.name }}</th>
                        <th> {{ course.room }}</th>
                        <th> {{ course.time }}</th>
                    </tr>
                </table>
            {% endfor %}
        {% endif %}
</div>
<div class="button submit-btn">
    <a href="{% url 'teacher_module:teacher_profile_view' %}">Go back</a>
</div>

{% endblock %}

dance_school_manager/templates/profiles/teacher/contact.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<div class="message centered">
    <h3>Contact Information</h3>
    <p>Email:   Tanczmy@gmail.com</p>
    <p>Email2:  RazemTanczmy@gmail.com</p>
    <p>Phone:   703742944</p>
    <p>Address: Ul. Taneczna 7</p>
</div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/course_page.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<div class="hello">
    <h2> Welcome {{ username }} to the "{{ certain_course.name }}" course page! </h2>
</div>
<div class="coursepage-container">
  <div class="coursepage-child left">
    <h2 class="title"> List of Participants</h2>
    <table class="title" style="width:100%">
            <tr>
                <th> Participant Name:</th>
                <th> Participant Email:</th>
            </tr>
        {% for student in students_attended %}
            <tr>
                <td> {{ student.username }}</td>
                <td> {{ student.email }}</td>
            </tr>
        {% endfor %}
    </table>
  </div>
  <div class="coursepage-child right">
    <h2 class="title"> Message box</h2>
    <table class="title" style="width:100%">
     <tr>
         <th> Title:</th>
         <th> Message:</th>
         <th> Date posted:</th>
     </tr>
     {% for messages in messages_assigned_to_this_course %}
     <tr>
         <td> {{ messages.title }} </td>
         <td> {{ messages.text }} </td>
         <td> {{ messages.date_created }} </td>

     </tr>
    {% endfor %}
    </table>
  </div>
</div>
<div>
     <p>
         <button class="submit-btn">
             <a href="{% url 'teacher_module:create_message_view' %}"> Write a message </a>
         </button>
    </p>
</div>
<div class="button submit-btn">
    <a href="{% url 'teacher_module:courses_view' %}">Go back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/courses.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<div class="course centered">
    <table>
     <tr>
                <th> Name of the course</th>
                <th> Description</th>
                <th> Course start date</th>
                <th> Course end date</th>
                <th> <p> Participants & Messages </p></th>

            </tr>
        {% for course in courses_list %}
            <tr>
                <td> {{ course.name }}</td>
                <td> {{ course.description }}</td>
                <td> {{ course.start_date }}</td>
                <td> {{ course.end_date }}</td>
                <th>
                <button>
                    <a href="{% url 'teacher_module:course_page_view' course_id=course.id %}"> Check details</a>
                </button>
                </th>

            </tr>
        {% endfor %}
    </table>
</div>
<div class="button submit-btn">
    <a href="{% url 'teacher_module:teacher_profile_view' %}">Go back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/create_message.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}
<div class="message centered">
    <h3>Write a Message</h3>
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Post"/>
        </form>
</div>
<div class="button submit-btn">
    <a href="{% url 'teacher_module:courses_view' %}">Go back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/school_courses_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dance_school_manager/templates/profiles/teacher/settings.html
{% extends 'profiles/teacher/base_generic.html' %}
{% block content %}

<style>
body {
  	text-align: center;
}
</style>


<div class="course centered">
	<div>
		<h3>Input your new data</h3>
		<div>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button class ="btn btn-secondary">Update</button>
            </form>
		</div>
	</div>
</div>
<div class="button submit-btn">
    <a href="{% url 'teacher_module:teacher_profile_view' %}">Go back</a>
</div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/teacher_profile.html
{% extends 'profiles/teacher/base_generic.html' %}

{% block content %}

<div class="contrainer">
    <div class="main">
        <div class="topbar">
            <button class="submit-btn" onclick="location.href = '/authentication/logout/'" type="button">
                LOGOUT
            </button>
            <button class="submit-btn" onclick="location.href = '{% url 'teacher_module:contact_view' %}'" type="button">
                CONTACT
            </button>
        </div>
        <div class="row">
            <div class="col-md-4 mt-1">
                <div class="card text-center sidebar">
                    <div class="card-body">
                            <img src="/static/images/profile.jpg" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h3>{{ user.username }}</h3>
                                <a href="{% url 'teacher_module:settings_view' %}">Edit Profile</a>
                                <a href="{% url 'teacher_module:calendar_view' %}">Calendar</a>
                                <a href="{% url 'teacher_module:courses_view' %}">Courses & Details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 mt-1">
                    <div class="card mb-3 content">
                        <h1 class="m-3 pt-3">About</h1>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <h5>Fist Name</h5>
                                </div>
                                <div class="col-md-9 text-secondary">
                                    {{ user.name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-md-3">
                                    <h5>Last Name</h5>
                                </div>
                                <div class="col-md-9 text-secondary">
                                    {{ user.surname }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-md-3">
                                    <h5>Email</h5>
                                </div>
                                <div class="col-md-9 text-secondary">
                                    {{ user.email }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </table>
    </div>
{% endblock %}

dance_school_manager/templates/profiles/teacher/teacher_profile_view.html
{% extends 'profiles/teacher/base_generic.html' %}

{% block content %}

{% endblock %}

dance_school_manager/templates/profiles/teacher/view_courses.html
{% block content %}
    <table>
        {% for course in courses_list %}
            <tr>
                <th> {{ course.name }}</th>
                <th> {{ course.description }}</th>

            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'teacher_module:teacher_profile_view' %}">Go back</a>
{% endblock %}
<body>
</body>